## This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
## For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path
#
#name: Maven Publish
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#          server-id: ossrh
#          server-username: MAVEN_USERNAME
#          server-password: MAVEN_PASSWORD
#
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
#
#      - name: Release
#        uses: qcastel/github-actions-maven-release@master
#        with:
#          release-branch-name: "master"
#          git-release-bot-name: "release-bot"
#          git-release-bot-email: "release-bot@example.com"
#          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
