name: Main Pipeline

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: ['*']
  workflow_dispatch:
    inputs:
      type:
        description: 'Release Library'
        required: true
        default: '...no release'
        type: choice
        options:
          - '...no release'
          - major
          - minor
          - patch

jobs:
  build:
    name: Build + JUnit Tests
    uses: ./.github/workflows/callable.build.yml
    if: | # avoid unnecessary pipeline runs during artifact release process ('gradle release plugin')
      !contains(github.event.head_commit.message, '[Gradle Release Plugin] - pre tag commit')
      || github.ref_type == 'tag'

  gradle_release:
    name: Create release
    uses: ./.github/workflows/callable.gradle-release.yml
    secrets: inherit
    with:
      type: ${{ inputs.type }}
    needs: build
    if: |
      github.event_name == 'workflow_dispatch'
      && inputs.type != '...no release'

  publish_sonatype:
    name: Publish artifact
    uses: ./.github/workflows/callable.publish-sonatype.yml
    secrets: inherit
    needs: gradle_release
    if: |
      (
        github.event_name != 'workflow_dispatch'
        || inputs.type == '...no release'
      ) && ( 
        github.ref == 'refs/heads/main' 
        || github.ref_type == 'tag' 
      )